#! /bin/sh

top_logging() {
  LOG_DIR=$1
  DURATION=$2

  if [ ! -e $LOG_DIR ]; then
    mkdir $LOG_DIR
  fi
 
  while :
  do
    DATEHOUR=`date +%Y%m%d_%H`
    FILE=$LOG_DIR'/'$DATEHOUR'.log'
    date +%Y%m%d_%H:%M:%S >> $FILE
    top -b -n 1 >> $FILE
    echo "" >> $FILE
  
    sleep $DURATION
  done
}

usage() {
  cat << EOF
found unknown options.
tmp_top_logging [-d <duration exec top command>] [-s <store num of versions>] [-f <path to log dir>]
EOF

exit 1
}

OS_NAME=`head -n 1 /etc/os-release`
OS=
DURATION=10
STORE_VERSION_NUM=3
LOG_DIR='/tmp/top'

while getopts d:s:f: OPT
do
  case $OPT in
    "d") DURATION=$OPTARG
          ;;
    "s") STORE_VERION_NUM=$OPTARG
          ;;
    "f") LOG_DIR=$OPTARG
          ;;
    "?") usage
          ;;
  esac
done

# check os
if echo $OS_NAME | grep -i 'ubuntu' >/dev/null; then
  OS=ubuntu
fi
echo $OS_NAME | grep -i centos
if echo $OS_NAME | grep -i 'centos' >/dev/null; then
  OS=centos
fi

if [ ! -n "$OS" ]; then
  echo "error: tmp_top_logging can use only ubuntu or centos."
  exit 1
fi

# create watch directory
if [ ! -e $LOG_DIR ]; then
  mkdir $LOG_DIR
fi

# check and exec tmp*** command.
if [ "$OS" = 'ubuntu' ]; then
  if type tmpreaper > /dev/null 2>&1; then
  :
  else
    exit 1
  fi

  tmpreaper $STORE_VERSION_NUM $LOG_DIR

elif [ "$OS" = 'centos' ];then
  if type tmpwatch > /dev/null 2>&1; then
  :
  else
    exit 1
  fi

  tmpwatch $STORE_VERSION_NUM $LOG_DIR
fi

# start logging
top_logging $LOG_DIR $DURATION
